# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

stages:
  - stage: Build
    displayName: Building the application
    jobs: 
      - job: Build
        pool: default
        steps: 
          - script: mvn clean install -DskipTests=true
            displayName: Building the app...
          - task: CopyFiles@2
            inputs:
              Contents: '**/*.war'
              TargetFolder: '$(build.artifactstagingdirectory)'
            displayName: copying the artifacts to staging directory
          - task: PublishBuildArtifacts@1
            inputs:
             PathtoPublish: '$(Build.ArtifactStagingDirectory)'
             ArtifactName: 'fleetman-wbapp'
             publishLocation: 'Container'
            displayName: Publishing the artifacts
          - task: Docker@2
            inputs:
              containerRegistry: 'acr0877'
              repository: 'fleetman'
              command: 'buildAndPush'
              Dockerfile: '**/Dockerfile'
            displayName: Building and pushing the images to ACR repo
          - task: CopyFiles@2
            inputs:
              Contents: '**/kube-manifests'
              TargetFolder: '$(build.artifactstagingdirectory)'
          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: '$(Build.ArtifactStagingDirectory)/kube-manifests'
              ArtifactName: 'manifests'
              publishLocation: 'Container'

          
           
           

