name: Build
on: workflow_dispatch # manually triggering workflow
jobs:
    my_first_job:
        runs-on: ubuntu-latest
        steps: 
            - uses: actions/checkout@v4
            - uses: actions/setup-java@v4
              with:
                distribution: 'zulu' # See 'Supported distributions' for available options
                java-version: '17'
            - run: mvn clean install -DskipTests 

    
    my_second_job:
        needs: my_first_job
        runs-on: ubuntu-latest
        steps: 
            - run: echo "second job"
    
    