name: Deployment 
on: 
    workflow_run: 
        workflows: Build and Sonar
        types: [completed]

jobs:
  Deploy:
    name: Deploy using Tomcat
    runs-on: ubuntu-latest
    steps: 
      - name: Download the build artifact from triggered workflow 
        uses: actions/download-artifact@v3
        with:
          name: fleetman-artifact
          path: 
        
      - run: |
          ls
          pwd
      - name: Deploy to Tomcat
        run: curl -v -u ${{secrets.TOMCAT_USR}}:${{secrets.TOMCAT_PWD}} -T /home/runner/work/fleetman-webapp/fleetman-webapp/target/fleetman-0.0.1-SNAPSHOT.war http://13.211.116.171:8080/manager/text/deploy?path=/spring-hello-war
      