name: Deployment 
on: 
    # workflow_run: 
    #     workflows: Build and Sonar
    #     types: [completed]

    workflow_dispatch: # manually triggering workflow
    inputs: 
      environment:
        description: Environment for deployment
        default: Dev
        required: true
        type: choice
        options:
            - Dev
            - Test
            - Prod
jobs:
  Deploy:
    environment: ${{github.event.inputs.environment}}
    name: Deploy using Tomcat
    runs-on: ubuntu-latest
    steps: 
      # - name: Download the build artifact from triggered workflow 
      #   uses: dawidd6/action-download-artifact@v2
      #   with:
      #     run_id: ${{ github.event.workflow_run.id }}
      #     path: ./fleetman
      #     search_artifacts: true
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: fleetman-artifact
          run-id: ${{ github.event.workflow_run.id }}
          path: ./fleetman
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          ls
          cd fleetman/
          ls
          cd */
          ls
          pwd
          
      - name: Deploy to Tomcat
        run: curl -v -u ${{secrets.TOMCAT_USR}}:${{secrets.TOMCAT_PWD}} -T /home/runner/work/fleetman-webapp/fleetman-webapp/fleetman/*/*.war http://54.206.111.223:8080/manager/text/deploy?path=/fleetman-webapp-war  
      