name: Build
on: workflow_dispatch # manually triggering workflow
jobs:
  Build Run:
    name: Build and Analyze
    runs-on: ubuntu-latest
    steps: 
      - name: Get code 
        uses: actions/checkout@v4
      - name: installing java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu' # See 'Supported distributions' for available options
          java-version: '17'
      - name: Cache SonarCloud packages
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build and analyze
        env:
          # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=Nimisha-Chonattil_fleetman-webapp -Dsonar.qualitygate.wait=true
      - name: uploading artifacts
        uses: actions/upload-artifact@v4
        with: 
          name: my-new-app
          path: target/*.war
      

    
    # my_second_job:
    #     needs: my_first_job
    #     runs-on: ubuntu-latest
    #     steps: 
    #         - run: echo "second job"
    
    